version: "3.3"

services:
  app:
    container_name: tt-app
    build: .
    depends_on:
      - mongo
    networks:
      - backend
    ports:
      - "${PORT}:${PORT}"
    expose:
      - ${PORT}
    env_file:
      - ./.env

  mongo:
    restart: always
    image: mongo:3
    container_name: tt-mongo
    volumes:
      - mongodata:/data/db
      - ./data/db/backup:/data/backup
    networks:
      - backend
    ports:
      - 27017:27017
    expose:
      - 27017

networks:
  backend:

volumes:
  mongodata:
